## Creating a Tensor

In [1]:
import torch

In [2]:
a=torch.empty(2,3)
a

tensor([[1.0812e+17, 9.7110e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [3]:
type(a)

torch.Tensor

In [4]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.rand(2, 3)

tensor([[0.2163, 0.0743, 0.5364],
        [0.0202, 0.3868, 0.7578]])

In [7]:
torch.tensor([[1,2,30],[2,3,54]])

tensor([[ 1,  2, 30],
        [ 2,  3, 54]])

In [8]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [9]:
torch.linspace(1, 10, 5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [10]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.full((4, 3), 5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

### Tensor Shapes

In [12]:
t = torch.tensor([[1,2,30],[2,3,54]])
t.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(t) # similarly torch.zeros_like, torch.ones_like

tensor([[0, 0, 0],
        [0, 0, 0]])

## Tensor Data Types

In [14]:
t.dtype

torch.int64

In [15]:
tx = torch.tensor([[1.3,2.4,30.32],[2,3,54]], dtype=torch.int64)
tx

tensor([[ 1,  2, 30],
        [ 2,  3, 54]])

In [16]:
torch.rand_like(t, dtype=torch.float)

tensor([[0.7076, 0.7892, 0.3169],
        [0.3980, 0.5318, 0.3739]])

## Mathematical operations

#### 1. Basic Operations

In [17]:
x = torch.rand(2, 3)
x

tensor([[0.4252, 0.3578, 0.8070],
        [0.7279, 0.6210, 0.9420]])

In [18]:
# addition
print(x + 2)
# Division
print(x/10)
# MOD
print(x % 2)
# exponent
print(x ** 2)

tensor([[2.4252, 2.3578, 2.8070],
        [2.7279, 2.6210, 2.9420]])
tensor([[0.0425, 0.0358, 0.0807],
        [0.0728, 0.0621, 0.0942]])
tensor([[0.4252, 0.3578, 0.8070],
        [0.7279, 0.6210, 0.9420]])
tensor([[0.1808, 0.1280, 0.6513],
        [0.5299, 0.3856, 0.8874]])


#### 2. Item-wise operation for 2 Tensors
- element wise mathematical operation i.e addion etc.
- can apply abs, round, floor, ceil, trunc, exp, sqrt, log, log10, sin, cos, tan

In [19]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.6651, 0.3059, 0.9127],
        [0.5853, 0.7186, 0.5092]])
tensor([[0.9453, 0.6131, 0.9117],
        [0.9173, 0.6613, 0.9104]])


In [20]:
# addition
print(a + b)

tensor([[1.6104, 0.9190, 1.8245],
        [1.5026, 1.3798, 1.4196]])


In [ ]:
c = torch.tensor([[1, -2, 3], [4, 5, -6]])
torch.abs(c)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [22]:
d = torch.tensor([1.5, 2.4, 3.78, 5.32])
torch.clamp(d, min=1.5, max=3.7) # clamp the values between 1.5 and 3.5

tensor([1.5000, 2.4000, 3.7000, 3.7000])

#### 3. Reduction Operation
- can calculate sum, mean, std, var, prod, min, max, median, mode


In [23]:
e = torch.randint(low=1, high=10,size=(2,3))
e

tensor([[3, 4, 3],
        [5, 1, 3]])

In [24]:
# can calculate sum, mean, std, var, prod, min, max, median, mode
torch.sum(e)   # sum of all elements

tensor(19)

In [25]:
print(torch.sum(e, dim=0)) # sum along the first dimension (columns)
print(torch.sum(e, dim=1)) # sum along the second dimension (rows)

tensor([8, 5, 6])
tensor([10,  9])


In [27]:
# argmax, argmin
print(torch.argmax(e)) # index of max value along the first dimension (columns)
print(torch.argmin(e)) # index of max value along the second dimension (rows)

tensor(3)
tensor(4)


#### 4. Matrix Operations

In [ ]:
mat1 = torch.randint(low=1, high=10,size=(2,3))
mat2 = torch.randint(low=1, high=10,size=(2,3))

print(mat1)
print(mat2)

tensor([[5, 8, 5],
        [2, 2, 7]])
tensor([[8, 2],
        [2, 4],
        [7, 5]])


In [31]:
# matrix multiplication
torch.matmul(mat1, mat2) # matrix multiplication

tensor([[91, 67],
        [69, 47]])

In [33]:
print(mat1) 
torch.transpose(mat1, 0, 1) # transpose of a matrix

tensor([[5, 8, 5],
        [2, 2, 7]])


tensor([[5, 2],
        [8, 2],
        [5, 7]])

In [ ]:
mat3 = torch.randint(low=1, high=10,size=(3,2,3))
mat3

tensor([[[3, 3],
         [7, 7],
         [2, 3]],

        [[9, 8],
         [5, 5],
         [5, 4]],

        [[4, 5],
         [4, 7],
         [7, 2]]])

In [43]:
mat4 = torch.randint(low=1, high=10,size=(3,3), dtype=torch.float)
mat4

tensor([[5., 5., 4.],
        [5., 3., 1.],
        [6., 3., 2.]])

In [44]:
torch.det(mat4) # determinant of a matrix

tensor(-17.0000)

In [45]:
torch.inverse(mat4) # inverse of a matrix

tensor([[-0.1765, -0.1176,  0.4118],
        [ 0.2353,  0.8235, -0.8824],
        [ 0.1765, -0.8824,  0.5882]])

#### 5. Comparison operator
- comparison operators like ==, !=, <, <=, >, >=


In [46]:
f = torch.randint(low=1, high=10,size=(2,3))
g = torch.randint(low=1, high=10,size=(2,3))

print(f)
print(g)

tensor([[8, 3, 2],
        [5, 6, 3]])
tensor([[2, 6, 4],
        [7, 4, 6]])


In [ ]:
f > g # element wise comparison, returns boolean tensor

tensor([[ True, False, False],
        [False,  True, False]])

#### 6. Inplace Operations

In [51]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)
print(m)
print(n)

tensor([[0.2601, 0.8615, 0.0575],
        [0.9801, 0.4226, 0.6752]])
tensor([[0.6946, 0.7677, 0.8738],
        [0.3010, 0.6520, 0.5423]])


In [ ]:
m + n # occupies new memory

tensor([[0.9547, 1.6292, 0.9313],
        [1.2812, 1.0746, 1.2175]])

In [54]:
print(m.add_(n)) # in place addition, modifies m
print(m) # m is modified

tensor([[1.6493, 2.3969, 1.8051],
        [1.5822, 1.7265, 1.7598]])
tensor([[1.6493, 2.3969, 1.8051],
        [1.5822, 1.7265, 1.7598]])


## Copying a tensor

In [55]:
h = torch.rand(size = (2,3), dtype=torch.float)
h

tensor([[0.0445, 0.8689, 0.1659],
        [0.8595, 0.6564, 0.9739]])

In [57]:
j = h.clone() # creates a copy of h
j

tensor([[0.0445, 0.8689, 0.1659],
        [0.8595, 0.6564, 0.9739]])

In [58]:
id(h), id(j) # different memory locations

(2017462772960, 2017463721152)

## Reshaping Tensors

#### reshape

In [60]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [61]:
a.reshape(2,8) # reshaping a tensor, returns a new tensor with same data but different shape

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

#### flatten

In [62]:
a.flatten() # flattening a tensor, returns a new tensor with same data but different shape

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### permute

In [64]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.7281, 0.1379, 0.5649, 0.3913],
         [0.5805, 0.6060, 0.6758, 0.0688],
         [0.0523, 0.0975, 0.9035, 0.4328]],

        [[0.2531, 0.3924, 0.0313, 0.4198],
         [0.4490, 0.7533, 0.6440, 0.7593],
         [0.1203, 0.7548, 0.6511, 0.9365]]])

In [ ]:
print(b.permute(2, 0, 1))# permuting the dimensions of a tensor, returns a new tensor with same data but different shape

print(b.permute(2, 0, 1).shape) # shape of the permuted tensor

tensor([[[0.7281, 0.5805, 0.0523],
         [0.2531, 0.4490, 0.1203]],

        [[0.1379, 0.6060, 0.0975],
         [0.3924, 0.7533, 0.7548]],

        [[0.5649, 0.6758, 0.9035],
         [0.0313, 0.6440, 0.6511]],

        [[0.3913, 0.0688, 0.4328],
         [0.4198, 0.7593, 0.9365]]])
torch.Size([4, 2, 3])


#### unsqeeze

In [ ]:
c = torch.rand(226, 226, 3)

# adding a new dimension at index 2, returns a new tensor with same data but different shape
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])