In [34]:
import torch
import torch.nn as nn

In [35]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(in_features=num_features, out_features=1)
        self.activation = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.activation(out)
        return out
    

In [36]:
# creating dataset

features = torch.rand(size=(10,5))
features

tensor([[0.9757, 0.6865, 0.7854, 0.5189, 0.1882],
        [0.2535, 0.8924, 0.1090, 0.6477, 0.1291],
        [0.1077, 0.4626, 0.2581, 0.2629, 0.9093],
        [0.9393, 0.3172, 0.7974, 0.2409, 0.0976],
        [0.4650, 0.8549, 0.0154, 0.6476, 0.0614],
        [0.7850, 0.1555, 0.9757, 0.0925, 0.2443],
        [0.4348, 0.9866, 0.2958, 0.0184, 0.3460],
        [0.3101, 0.4739, 0.8107, 0.9994, 0.5760],
        [0.1760, 0.4787, 0.6213, 0.4269, 0.7739],
        [0.8353, 0.6188, 0.7342, 0.7033, 0.2109]])

In [37]:
model = Model(num_features=features.shape[1])
model(features)

tensor([[0.4784],
        [0.4916],
        [0.5044],
        [0.4477],
        [0.4764],
        [0.4522],
        [0.5397],
        [0.4694],
        [0.5017],
        [0.4662]], grad_fn=<SigmoidBackward0>)

In [38]:
model.linear.weight

Parameter containing:
tensor([[-0.1029,  0.4365,  0.1158, -0.1748,  0.1780]], requires_grad=True)

In [39]:
# visualizing the model
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### NN with hidden layer

In [40]:
class ModelHiddenLayer(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(in_features=num_features, out_features=3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [41]:
features = torch.rand(size=(10,5))
features

tensor([[0.0558, 0.5933, 0.6884, 0.8326, 0.9219],
        [0.2470, 0.9866, 0.1067, 0.6396, 0.8304],
        [0.9635, 0.3628, 0.3881, 0.1085, 0.7821],
        [0.1633, 0.2912, 0.9241, 0.1626, 0.4685],
        [0.9463, 0.4571, 0.7873, 0.3149, 0.0678],
        [0.5931, 0.0094, 0.4976, 0.0324, 0.4265],
        [0.3835, 0.3181, 0.7072, 0.2922, 0.5401],
        [0.3375, 0.2142, 0.2097, 0.3621, 0.2863],
        [0.8095, 0.9285, 0.4627, 0.3296, 0.5347],
        [0.0403, 0.6732, 0.8091, 0.9054, 0.7117]])

In [42]:
model = ModelHiddenLayer(num_features=5)
model(features)

tensor([[0.3456],
        [0.3241],
        [0.3936],
        [0.3978],
        [0.4145],
        [0.4148],
        [0.3794],
        [0.3938],
        [0.3682],
        [0.3464]], grad_fn=<SigmoidBackward0>)

In [43]:
model.linear2.weight

Parameter containing:
tensor([[ 0.5588, -0.4696, -0.2767]], requires_grad=True)

In [44]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelHiddenLayer                         [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Sequential Container

In [45]:
class ModelSeq(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [46]:
model = ModelSeq(num_features=5)
model(features)

tensor([[0.4561],
        [0.4551],
        [0.4669],
        [0.4670],
        [0.4669],
        [0.4674],
        [0.4667],
        [0.4676],
        [0.4673],
        [0.4524]], grad_fn=<SigmoidBackward0>)

In [47]:
model.network[0].weight

Parameter containing:
tensor([[-0.4186,  0.4018,  0.0753, -0.0006,  0.0274],
        [ 0.3066, -0.3659, -0.2936, -0.2116,  0.1025],
        [ 0.1330, -0.1656,  0.2509,  0.3997,  0.2399]], requires_grad=True)

In [48]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelSeq                                 [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00